### ISSUE TITLE
Error while starting...screenshot attached for your reference

### ISSUE THREAD

**Issue by unixbhaskar** [dstein64/vim-startuptime#1]
![2020-01-28-145932_1366x768_scrot](https://user-images.githubusercontent.com/113643/73251417-efcdab80-41de-11ea-85c8-e18cb7240288.png)

**Comment by dstein64** [comment]
Is your Vim compiled with terminal support?

This can be checked with either 1) `:version` or 2) seeing if `:echo has('terminal')` returns `1`.

If not, it looks like `terminal` support can be enabled with `USE flags` on Gentoo.
https://wiki.gentoo.org/wiki/Vim#USE_flags

**Comment by dstein64** [comment]
I've updated the plugin so that it will fail fast with a relevant error if `+terminal` support is missing.

**Comment by unixbhaskar** [comment]
...and it does work ...thanks @dstein64 :)
![2020-01-29-040005_1366x768_scrot](https://user-images.githubusercontent.com/113643/73311206-e9c1e400-424b-11ea-983e-bf64de1598d4.png)

**Comment by dstein64** [comment]
Thanks again for reporting. In addition to checking for `+terminal`, I've added a few more checks that will cause the plugin to _fail fast_ if necessary, with a corresponding error message (e.g, requiring `+startuptime`). I've also updated the _Requirements_.
