### ISSUE TITLE
Not working in neovim

### ISSUE THREAD

**Issue by Aetf** [dstein64/vim-startuptime#12]
The `:StartupTime` command just opens a vsplit with

```
# vim-startuptime
Running: [0%]
```

And then nothing happens.

My neovim version is 0.6.1. This could be a configuration issue from my side, as I'm lazy loading this plugin on command execution. But there isn't any log or error. So I'm not sure how to proceed to debug this.

**Comment by dstein64** [comment]
Thanks for reporting this @Aetf!

Can you share the operating system you encounted this on and post the first few lines of output from `:version`?

E.g.,
```
:version
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Does Neovim load properly when you launch it from within Neovim with `:terminal nvim`? Are there any prompts or notifications that interfere with starting up?

**Comment by Aetf** [comment]
Here you go
```
:version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

And `:terminal nvim` ~~loads properly without error or prompts~~. I'm running vim from a project folder, so the auto session restore kicks in and complains that the file was already opened in another instance.

Starting vim from a folder without session and then `:StartupTime` works beautifully!
