### ISSUE TITLE
Error - [vim-plug] vim-startuptime Invalid argument: vim-startuptime (implicit `vim-scripts' expansion is deprecated)

### ISSUE THREAD

**Issue by eggbean** [dstein64/vim-startuptime#17]
This isn't working for me on vim 9.0 or nvim 0.7.2 on Linux.

**Comment by dstein64** [comment]
Thanks for reporting the issue @eggbean! Can you provide more details on where the error message is appearing? Does this happen immediately after calling `:StartupTime`?

**Comment by eggbean** [comment]
In nvim it appears immediately on startup in red at the bottom command line. In vim on startup, before the program starts it appears in the shell command line with `Press ENTER or type command to continue` afterwards.

As it's happening on both programs and you are unaware of this problem, I suspect it could be due to something in my configuration, which is shared between both of them.

**Comment by dstein64** [comment]
What's the line you use to specify the plugin in your config?

E.g.,
```vim
Plug 'dstein64/vim-startuptime'
```

**Comment by eggbean** [comment]
Oh wow, I'm so embarrassed. Good call, yes I missed your name out. Sorry. 😳
