### ISSUE TITLE
Feature Request: Allow to open a  preexisting log file 

### ISSUE THREAD

**Issue by ecerulm** [dstein64/vim-startuptime#19]
I have a preexisting file `vim.log` that I obtained with `vim --startuptime vim.log xxxxx.txt`

I would like to `:StartupTime vim.log` to get the visualization of that file. 

Rationale: My vim sometimes is very slow to startup. Sometimes not always, and I have been able to reproduce with `vim --startuptime vim.log xxx.txt` but not with `:StartupTime` alone. Hence I would like to be able to open the `vim.log` file that I generated and analyze it.

**Comment by dstein64** [comment]
Hi @ecerulm. I added an `--input-file` option for specifying a file that was generated by running `(n)vim` with the `--startuptime` argument.

```vim
:StartupTime --input-file /some/path/to/startuptime/file
```

**Comment by bassamsdata** [comment]
this is an amazing feature, thank you
