### ISSUE TITLE
--self argument isn't implemented

### ISSUE THREAD

**Issue by idbrii** [dstein64/vim-startuptime#2]
`StartupTime --self --tries 10` produces:
|| Error detected while processing function
|| startuptime#StartupTime[8]
|| <SNR>264_Options[22]
|| E605: Exception not caught: vim-startuptime: unknown argument (--self)

Looking at the code, `--self` isn't implemented in the options parser.
https://github.com/dstein64/vim-startuptime/blob/master/autoload/startuptime.vim#L541-L555

**Comment by dstein64** [comment]
Thanks for reporting!

This is fixed as of 38b6e0b8069f67c19389c113e11b69fbf9448b5a.
