### ISSUE TITLE
Set filetype to allow easier mapping customization

### ISSUE THREAD

**Issue by wbthomason** [dstein64/vim-startuptime#3]
Could you please add `set filetype=startuptime` or similar for the startuptime buffer? This would be useful e.g. for making a `ftplugin` to set up additional mappings for the startuptime results buffer (such as mapping `q` to quit the buffer, etc.)

**Comment by dstein64** [comment]
Good idea. Thanks!

The `vim-startuptime` buffer now has `filetype=startuptime` (3dbec6d2c9fc97ec12b2391c6b92208179bc36c4).
