### ISSUE TITLE
setting variable g:startuptime_tries bigger than 1 results in an error frequtently

### ISSUE THREAD

**Issue by jdhao** [dstein64/vim-startuptime#5]
If we set the variable `g:startuptime_tries` to other values than 1, when I run command `:StartupTime`, I saw the following error almost all the time:

> Error detected while processing function 15[1]..<SNR>118_Profile[2]..startuptime#Main[9]..<SNR>118_Consolidate:   
line    9:                                                                                                        
E605: Exception not caught: vim-startuptime: inconsistent tries                                                   

Sometimes, this command does succeed, but rarely. 

+ Nvim version: `NVIM v0.5.0-dev+1459-g384f9870f `
+ OS: Linux CentOS 7.4
+ vim-startuptime version: Latest master

**Comment by dstein64** [comment]
Thanks for reporting this!

The code was assuming that the events reported when using Vim's `--startuptime` are consistent across multiple invocations (in both the events themselves and their ordering). I've updated the code to no longer make this assumption.
